-- ============================================================
-- 7iTAX Full Schema (22 tables)
-- PostgreSQL 16
-- ============================================================

-- ============================================================
-- 1. users
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    biometric_enabled BOOLEAN     NOT NULL,
    birth_date      DATE,
    ci              VARCHAR(128) NOT NULL UNIQUE,
    device_id       VARCHAR(255),
    di              VARCHAR(128) NOT NULL UNIQUE,
    gender          VARCHAR(255),
    is_business     BOOLEAN      NOT NULL,
    kyc_verified    BOOLEAN      NOT NULL,
    last_login_at   TIMESTAMP(6),
    name            VARCHAR(512),
    phone_last4     VARCHAR(4),
    phone_number    VARCHAR(512),
    pin_hash        VARCHAR(200),
    ssafy_user_key  VARCHAR(100),
    status          VARCHAR(255) NOT NULL
                        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

CREATE INDEX IF NOT EXISTS idx_user_phone_last4 ON users (phone_last4);

-- ============================================================
-- 2. business_profiles
-- ============================================================
CREATE TABLE IF NOT EXISTS business_profiles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6),
    business_name       VARCHAR(255),
    business_reg_number VARCHAR(512),
    industry_code       VARCHAR(255),
    nts_verified        BOOLEAN     NOT NULL,
    nts_verified_at     TIMESTAMP(6),
    user_id             BIGINT      NOT NULL UNIQUE,
    CONSTRAINT fk_bp_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ============================================================
-- 3. user_consents
-- ============================================================
CREATE TABLE IF NOT EXISTS user_consents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    consent_type    VARCHAR(255) NOT NULL
                        CHECK (consent_type IN ('SERVICE', 'PRIVACY', 'FINANCIAL')),
    consented       BOOLEAN      NOT NULL,
    consented_at    TIMESTAMP(6),
    revoked_at      TIMESTAMP(6),
    user_id         BIGINT       NOT NULL,
    CONSTRAINT uq_user_consent UNIQUE (user_id, consent_type),
    CONSTRAINT fk_uc_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_consent_user_id ON user_consents (user_id);

-- ============================================================
-- 4. cards
-- ============================================================
CREATE TABLE IF NOT EXISTS cards (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              TIMESTAMP(6),
    updated_at              TIMESTAMP(6),
    card_expiry_date        VARCHAR(255),
    card_name               VARCHAR(255) NOT NULL,
    card_no                 VARCHAR(512) NOT NULL,
    card_type               VARCHAR(255) NOT NULL
                                CHECK (card_type IN ('PERSONAL', 'BUSINESS')),
    card_unique_no          VARCHAR(255) NOT NULL,
    cvc                     VARCHAR(512) NOT NULL,
    deleted                 BOOLEAN      NOT NULL,
    is_default              BOOLEAN      NOT NULL,
    last4digits             VARCHAR(4)   NOT NULL,
    withdrawal_account_no   VARCHAR(255),
    withdrawal_date         VARCHAR(255),
    user_id                 BIGINT       NOT NULL,
    CONSTRAINT fk_card_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_card_user_id ON cards (user_id);

-- ============================================================
-- 5. card_transactions
-- ============================================================
CREATE TABLE IF NOT EXISTS card_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6),
    amount              BIGINT       NOT NULL,
    balance_after       BIGINT       NOT NULL,
    description         VARCHAR(255),
    transaction_type    VARCHAR(255) NOT NULL
                            CHECK (transaction_type IN ('CHARGE', 'PAYMENT', 'REFUND')),
    card_id             BIGINT       NOT NULL,
    CONSTRAINT fk_ct_card FOREIGN KEY (card_id) REFERENCES cards(id)
);

-- ============================================================
-- 6. payments
-- ============================================================
CREATE TABLE IF NOT EXISTS payments (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                  TIMESTAMP(6),
    updated_at                  TIMESTAMP(6),
    amount                      BIGINT       NOT NULL,
    authorization_code          VARCHAR(255),
    authorized_at               TIMESTAMP(6),
    cancel_reason               VARCHAR(255),
    cancelled_amount            BIGINT,
    cancelled_at                TIMESTAMP(6),
    captured_at                 TIMESTAMP(6),
    currency                    VARCHAR(255) NOT NULL,
    merchant_category_code      VARCHAR(255),
    merchant_id                 BIGINT,
    merchant_name               VARCHAR(255) NOT NULL,
    payment_method              VARCHAR(255) NOT NULL
                                    CHECK (payment_method IN ('ONLINE', 'OFFLINE')),
    purpose                     VARCHAR(255) NOT NULL
                                    CHECK (purpose IN ('PERSONAL', 'BUSINESS')),
    ssafy_transaction_unique_no BIGINT,
    status                      VARCHAR(255) NOT NULL
                                    CHECK (status IN ('AUTHORIZED', 'CAPTURED', 'CANCELLED', 'DECLINED')),
    card_id                     BIGINT       NOT NULL,
    user_id                     BIGINT       NOT NULL,
    CONSTRAINT fk_pay_card FOREIGN KEY (card_id) REFERENCES cards(id),
    CONSTRAINT fk_pay_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_payment_user_id     ON payments (user_id);
CREATE INDEX IF NOT EXISTS idx_payment_card_id     ON payments (card_id);
CREATE INDEX IF NOT EXISTS idx_payment_status      ON payments (status);
CREATE INDEX IF NOT EXISTS idx_payment_user_status ON payments (user_id, status);

-- ============================================================
-- 7. transfers
-- ============================================================
CREATE TABLE IF NOT EXISTS transfers (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                  TIMESTAMP(6),
    updated_at                  TIMESTAMP(6),
    amount                      BIGINT       NOT NULL,
    description                 VARCHAR(255),
    ssafy_transaction_unique_no VARCHAR(255),
    status                      VARCHAR(255) NOT NULL
                                    CHECK (status IN ('COMPLETED', 'FAILED')),
    target_account_no           VARCHAR(255),
    transfer_type               VARCHAR(255) NOT NULL
                                    CHECK (transfer_type IN ('P2P', 'WITHDRAW')),
    receiver_card_id            BIGINT,
    receiver_user_id            BIGINT,
    sender_card_id              BIGINT       NOT NULL,
    sender_user_id              BIGINT       NOT NULL,
    CONSTRAINT fk_tf_sender_card   FOREIGN KEY (sender_card_id)   REFERENCES cards(id),
    CONSTRAINT fk_tf_sender_user   FOREIGN KEY (sender_user_id)   REFERENCES users(id),
    CONSTRAINT fk_tf_receiver_card FOREIGN KEY (receiver_card_id) REFERENCES cards(id),
    CONSTRAINT fk_tf_receiver_user FOREIGN KEY (receiver_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_transfer_sender_user   ON transfers (sender_user_id);
CREATE INDEX IF NOT EXISTS idx_transfer_receiver_user ON transfers (receiver_user_id);

-- ============================================================
-- 8. book_entries
-- ============================================================
CREATE TABLE IF NOT EXISTS book_entries (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6),
    category_code       VARCHAR(10),
    category_name       VARCHAR(50),
    confirmed           BOOLEAN      NOT NULL,
    confirmed_at        TIMESTAMP(6),
    description         VARCHAR(500),
    entry_date          DATE         NOT NULL,
    entry_type          VARCHAR(10)  NOT NULL
                            CHECK (entry_type IN ('INCOME', 'EXPENSE', 'ASSET')),
    expense_amount      BIGINT       NOT NULL,
    fixed_asset_amount  BIGINT       NOT NULL,
    income_amount       BIGINT       NOT NULL,
    is_business_expense BOOLEAN      NOT NULL,
    is_vat_deductible   BOOLEAN      NOT NULL,
    merchant_name       VARCHAR(200),
    note                VARCHAR(500),
    payment_id          BIGINT       UNIQUE,
    supply_price        BIGINT       NOT NULL,
    user_id             BIGINT       NOT NULL,
    vat_amount          BIGINT       NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_be_user_date      ON book_entries (user_id, entry_date DESC);
CREATE INDEX IF NOT EXISTS idx_be_user_confirmed ON book_entries (user_id, confirmed);

-- ============================================================
-- 9. tax_returns
-- ============================================================
CREATE TABLE IF NOT EXISTS tax_returns (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6),
    accepted_at         TIMESTAMP(6),
    calculated_tax      BIGINT       NOT NULL,
    deductions_json     TEXT,
    determined_tax      BIGINT       NOT NULL,
    final_tax           BIGINT       NOT NULL,
    income_amount       BIGINT       NOT NULL,
    local_tax           BIGINT       NOT NULL,
    prepaid_tax         BIGINT       NOT NULL,
    receipt_number      VARCHAR(255) UNIQUE,
    resident_number     VARCHAR(255),
    status              VARCHAR(255) NOT NULL
                            CHECK (status IN ('DRAFT', 'SUBMITTED', 'ACCEPTED', 'PAID', 'COMPLETED')),
    submitted_at        TIMESTAMP(6),
    tax_rate            DOUBLE PRECISION NOT NULL,
    tax_year            INTEGER      NOT NULL,
    taxable_income      BIGINT       NOT NULL,
    taxpayer_name       VARCHAR(255),
    total_deductions    BIGINT       NOT NULL,
    total_expense       BIGINT       NOT NULL,
    total_revenue       BIGINT       NOT NULL,
    user_id             BIGINT       NOT NULL,
    version             BIGINT
);

CREATE INDEX IF NOT EXISTS idx_tax_return_user_year ON tax_returns (user_id, tax_year);

-- ============================================================
-- 10. expense_details
-- ============================================================
CREATE TABLE IF NOT EXISTS expense_details (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount          BIGINT       NOT NULL,
    expense_code    VARCHAR(255) NOT NULL,
    expense_name    VARCHAR(255) NOT NULL,
    tax_return_id   BIGINT       NOT NULL,
    CONSTRAINT fk_ed_tax_return FOREIGN KEY (tax_return_id) REFERENCES tax_returns(id)
);

-- ============================================================
-- 11. tax_payments
-- ============================================================
CREATE TABLE IF NOT EXISTS tax_payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    amount          BIGINT       NOT NULL,
    error_message   VARCHAR(255),
    from_account    VARCHAR(255),
    paid_at         TIMESTAMP(6),
    payment_type    VARCHAR(255) NOT NULL
                        CHECK (payment_type IN ('NATIONAL', 'LOCAL')),
    status          VARCHAR(255) NOT NULL
                        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    transfer_id     VARCHAR(255),
    virtual_account VARCHAR(255),
    virtual_bank    VARCHAR(255),
    tax_return_id   BIGINT       NOT NULL,
    CONSTRAINT uq_tax_payment_return_type UNIQUE (tax_return_id, payment_type),
    CONSTRAINT fk_tp_tax_return FOREIGN KEY (tax_return_id) REFERENCES tax_returns(id)
);

CREATE INDEX IF NOT EXISTS idx_tax_payment_tax_return ON tax_payments (tax_return_id);

-- ============================================================
-- 12. vat_returns
-- ============================================================
CREATE TABLE IF NOT EXISTS vat_returns (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    final_tax       BIGINT       NOT NULL,
    preliminary_paid BIGINT      NOT NULL,
    purchase_amount BIGINT       NOT NULL,
    purchase_tax    BIGINT       NOT NULL,
    receipt_number  VARCHAR(255) UNIQUE,
    sales_amount    BIGINT       NOT NULL,
    sales_tax       BIGINT       NOT NULL,
    status          VARCHAR(255) NOT NULL
                        CHECK (status IN ('DRAFT', 'SUBMITTED', 'ACCEPTED', 'PAID', 'COMPLETED')),
    submitted_at    TIMESTAMP(6),
    tax_period      INTEGER      NOT NULL,
    tax_year        INTEGER      NOT NULL,
    user_id         BIGINT       NOT NULL,
    CONSTRAINT uq_vat_return_user_year_period UNIQUE (user_id, tax_year, tax_period)
);

CREATE INDEX IF NOT EXISTS idx_vat_return_user_year ON vat_returns (user_id, tax_year);

-- ============================================================
-- 13. tax_brackets
-- ============================================================
CREATE TABLE IF NOT EXISTS tax_brackets (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bracket_max             BIGINT           NOT NULL,
    bracket_min             BIGINT           NOT NULL,
    progressive_deduction   BIGINT           NOT NULL,
    rate                    DOUBLE PRECISION NOT NULL,
    year                    INTEGER          NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tb_year ON tax_brackets (year);

-- ============================================================
-- 14. merchant (가맹점 마스터)
-- ============================================================
CREATE TABLE IF NOT EXISTS merchant (
    id              BIGSERIAL       PRIMARY KEY,
    merchant_name   VARCHAR(200)    NOT NULL,
    mcc             VARCHAR(10)     NOT NULL,
    category        VARCHAR(100),
    example_names   TEXT,
    is_domestic     BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_merchant_mcc  ON merchant (mcc);
CREATE INDEX IF NOT EXISTS idx_merchant_name ON merchant (merchant_name);

-- ============================================================
-- 15. mcc_tax_rule (MCC -> 세목 매핑 룰)
-- ============================================================
CREATE TABLE IF NOT EXISTS mcc_tax_rule (
    id                    BIGSERIAL       PRIMARY KEY,
    mcc                   VARCHAR(10)     NOT NULL,
    tier                  VARCHAR(1)      NOT NULL CHECK (tier IN ('A', 'B')),
    condition_expr        TEXT,
    tax_category          VARCHAR(50)     NOT NULL,
    vat_deductible        VARCHAR(30)     NOT NULL DEFAULT '확인필요',
    amount_threshold      BIGINT,
    remark                TEXT,
    legal_basis           VARCHAR(200),
    annual_limit          BIGINT,
    confidence            INTEGER,
    requires_user_confirm BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE INDEX  IF NOT EXISTS idx_mcc_tax_rule_mcc ON mcc_tax_rule (mcc);
CREATE INDEX  IF NOT EXISTS idx_mcc_tax_rule_tier ON mcc_tax_rule (tier);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mcc_tax_rule_mcc_condition ON mcc_tax_rule (mcc, COALESCE(condition_expr, ''));

-- ============================================================
-- 16. merchant_keyword_mapping (가맹점 키워드 매칭)
-- ============================================================
CREATE TABLE IF NOT EXISTS merchant_keyword_mapping (
    id              BIGSERIAL       PRIMARY KEY,
    keyword         VARCHAR(100)    NOT NULL,
    mcc             VARCHAR(10)     NOT NULL DEFAULT '5817',
    tax_category    VARCHAR(50)     NOT NULL,
    is_domestic     BOOLEAN         NOT NULL DEFAULT TRUE,
    confidence      INTEGER,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT uq_keyword_mcc UNIQUE (keyword, mcc)
);

CREATE INDEX IF NOT EXISTS idx_mkm_keyword      ON merchant_keyword_mapping (keyword);
CREATE INDEX IF NOT EXISTS idx_mkm_tax_category ON merchant_keyword_mapping (tax_category);

-- ============================================================
-- 17. tax_limit (세목별 한도/알림 룰)
-- ============================================================
CREATE TABLE IF NOT EXISTS tax_limit (
    id              BIGSERIAL       PRIMARY KEY,
    tax_category    VARCHAR(50)     NOT NULL,
    limit_type      VARCHAR(50)     NOT NULL,
    limit_amount    BIGINT          NOT NULL DEFAULT 0,
    unit            VARCHAR(20)     NOT NULL,
    legal_basis     VARCHAR(200),
    alert_message   VARCHAR(500),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tax_limit_category ON tax_limit (tax_category);
CREATE INDEX IF NOT EXISTS idx_tax_limit_type     ON tax_limit (limit_type);

-- ============================================================
-- 18. accounts (계좌)
-- ============================================================
CREATE TABLE IF NOT EXISTS accounts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              TIMESTAMP(6),
    updated_at              TIMESTAMP(6),
    account_no              VARCHAR(512) NOT NULL,
    account_type            VARCHAR(255) NOT NULL
                                CHECK (account_type IN ('PERSONAL', 'BUSINESS')),
    account_type_unique_no  VARCHAR(255) NOT NULL,
    alias                   VARCHAR(255),
    bank_code               VARCHAR(255) NOT NULL,
    deleted                 BOOLEAN      NOT NULL DEFAULT FALSE,
    status                  VARCHAR(255) NOT NULL
                                CHECK (status IN ('ACTIVE', 'INACTIVE', 'CLOSED')),
    user_id                 BIGINT       NOT NULL,
    CONSTRAINT fk_account_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_account_user_id ON accounts (user_id);

-- ============================================================
-- 19. chat_sessions (AI 채팅 세션)
-- ============================================================
CREATE TABLE IF NOT EXISTS chat_sessions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    session_id      VARCHAR(255) NOT NULL UNIQUE,
    user_id         BIGINT       NOT NULL,
    message_count   INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_cs_user_id    ON chat_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_cs_session_id ON chat_sessions (session_id);

-- ============================================================
-- 20. chat_messages (AI 채팅 메시지)
-- ============================================================
CREATE TABLE IF NOT EXISTS chat_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6),
    content         TEXT         NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    session_id      VARCHAR(255) NOT NULL,
    CONSTRAINT fk_cm_session FOREIGN KEY (session_id) REFERENCES chat_sessions(session_id)
);

CREATE INDEX IF NOT EXISTS idx_cm_session_id ON chat_messages (session_id);

-- ============================================================
-- 21. tax_parameters (세금 정책 파라미터)
-- ============================================================
CREATE TABLE IF NOT EXISTS tax_parameters (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    "year"          INTEGER       NOT NULL,
    category        VARCHAR(50)   NOT NULL,
    param_key       VARCHAR(100)  NOT NULL,
    param_value     VARCHAR(200)  NOT NULL,
    description     VARCHAR(500),
    legal_basis     VARCHAR(200),
    CONSTRAINT uk_tax_param_year_cat_key UNIQUE ("year", category, param_key)
);

CREATE INDEX IF NOT EXISTS idx_tax_param_year_cat ON tax_parameters ("year", category);

-- ============================================================
-- 22. tax_deadlines (세금 신고 기한)
-- ============================================================
CREATE TABLE IF NOT EXISTS tax_deadlines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    "year"          INTEGER       NOT NULL,
    name            VARCHAR(100)  NOT NULL,
    description     VARCHAR(500),
    deadline_month  INTEGER       NOT NULL,
    deadline_day    INTEGER       NOT NULL,
    CONSTRAINT uk_tax_deadline_year_name UNIQUE ("year", name)
);

CREATE INDEX IF NOT EXISTS idx_tax_deadline_year ON tax_deadlines ("year");
