@sessionId = addaa282b8cd46fda54bd798a054d8a6

## 채팅 요청
POST http://localhost:8000/api/v1/chat/
Content-Type: application/

{
  "message": "종합소득세가 뭐야?"
}

###

## 세션 유지
POST http://localhost:8000/api/v1/chat/
Content-Type: application/json

{
  "message": "더 자세히 알려줘",
  "session_id": "{{sessionId}}"
}

###

## 대화 히스토리 조회

GET http://localhost:8000/api/v1/chat/history/{{sessionId}}
